---
driver:
  name: dokken
  privileged: true

provisioner:
  name: dokken

transport:
 name: dokken

verifier:
 name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
     pid_one_command: /usr/lib/systemd/systemd
     intermediate_instructions:
      - RUN apt-get install -y lsof which net-tools iproute
  - name: centos-7
    driver:
     platform: rhel
     pid_one_command: /usr/lib/systemd/systemd
     intermediate_instructions:
      - RUN yum clean all
      - RUN yum -y install lsof which net-tools iproute

suites:
  - name: default
    run_list:
      - recipe[apache-server::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
